- pom.xml
> Drop corporate Maven profile.

- factcast-client-grpc/src/main/java/org/factcast/client/grpc/GrpcFactStore.java
> codacy improvement

- factcast-store-pgsql-rds/src/main/java/org/factcast/store/pgsql/rds/RdsDataSourceFactoryBeanPostProcessor.java
- factcast-store-pgsql-rds/src/test/java/org/factcast/store/pgsql/rds/RdsDataSourceFactoryBeanPostProcessorTest.java
> Set higher priority for RdsDataSourceFactoryBeanPostProcessor

- factcast-core/pom.xml
> #496: exclude accidentally shaded artifacts

- factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/PgFactStore.java
> codacy suggestion

- factcast-core/pom.xml
> #657: stop shading jackson into core

- .githooks/pre-commit.d/spotless
- factcast-schema-registry-cli/pom.xml
> #661: updated jackson dependency

- factcast-schema-registry-cli/pom.xml
- factcast-schema-registry-cli/src/main/kotlin/org/factcast/schema/registry/cli/fs/FileSystemServiceImpl.kt
> added javax.annotation dependency for Java11 compatibility

- factcast-server-grpc/src/main/java/org/factcast/server/grpc/FactCastSecurityConfiguration.java
> Fixed non-matching passwords for unauthenticated access

- factcast-spring-boot-autoconfigure/src/main/java/org/factcast/spring/boot/autoconfigure/store/pgsql/FactValidatorAutoConfiguration.java
- factcast-spring-boot-autoconfigure/src/main/resources/META-INF/spring.factories
> Add autoconfiguration for FactValidatorConfiguration

- factcast-core/src/main/java/org/factcast/core/spec/FactSpec.java
- factcast-core/src/main/java/org/factcast/core/spec/FactSpecMatcher.java
- factcast-core/src/main/java/org/factcast/core/spec/RenameMe.java
- factcast-core/src/main/java/org/factcast/core/spec/Specification.java
- factcast-core/src/test/java/org/factcast/core/spec/FactSpecMatcherTest.java
- factcast-core/src/test/java/org/factcast/core/spec/FactSpecTest.java
created convenient method to create FactSpec
> WIP #715-factspec: added version to FactSpec

- pom.xml
> #921: use gitflow maven plugin

- factcast-spring-boot-autoconfigure/src/main/java/org/factcast/spring/boot/autoconfigure/client/grpc/LZ4ClientAutoConfiguration.java
- factcast-spring-boot-autoconfigure/src/main/java/org/factcast/spring/boot/autoconfigure/client/grpc/SnappyClientAutoConfiguration.java
- factcast-spring-boot-autoconfigure/src/main/java/org/factcast/spring/boot/autoconfigure/core/FactCastAutoConfiguration.java
- factcast-spring-boot-autoconfigure/src/main/java/org/factcast/spring/boot/autoconfigure/core/FactCastSnapshotCacheAutoConfiguration.java
- factcast-spring-boot-autoconfigure/src/main/java/org/factcast/spring/boot/autoconfigure/core/RedissonSnapshotCacheAutoConfiguration.java
- factcast-spring-boot-autoconfigure/src/main/java/org/factcast/spring/boot/autoconfigure/highlevel/FactusAutoConfiguration.java
- factcast-spring-boot-autoconfigure/src/main/java/org/factcast/spring/boot/autoconfigure/server/grpc/LZ4ServerAutoConfiguration.java
- factcast-spring-boot-autoconfigure/src/main/java/org/factcast/spring/boot/autoconfigure/server/grpc/SnappyServerAutoConfiguration.java
> Issue1023 @ConditionalOnMissingBean on autoconfiguration

- factcast-site/documentation/content/factus/snapshot-projections.md
First fix, just updated the docs. Hope that was the solution that helped so far :)
> Docs updated

- factcast-test/pom.xml
- factcast-test/src/main/java/org/factcast/test/AbstractFactCastIntegrationTest.java
- factcast-test/src/main/java/org/factcast/test/RedisEraser.java
- factcast-test/src/main/java/org/factcast/test/RedisExtension.java
- introduce RedisExtension that clears all keys in redis
- this also fixes wrong env var names in AbstractFactCastIntegrationTest
> #1071: introduce RedisExtension that clears all keys in redis

- factcast-schema-registry-cli/src/main/kotlin/org/factcast/schema/registry/cli/validation/formatErrors.kt
See commit comments for details
> Fixes #827 and improves other error message

- factcast-snapshotcache-redisson/src/main/java/org/factcast/core/snap/redisson/RedissonSnapshotCache.java
- factcast-snapshotcache-redisson/src/test/java/org/factcast/core/snap/redisson/RedissonSnapshotCacheTest.java
- factcast-spring-boot-autoconfigure/src/main/java/org/factcast/spring/boot/autoconfigure/core/RedissonSnapshotCacheAutoConfiguration.java
- lombok.config
@Scheduled-annotated methods should have no arguments
> Fixed Scheduled

- factcast-schema-registry-cli/src/main/kotlin/org/factcast/schema/registry/cli/commands/CommandServiceImpl.kt
- factcast-schema-registry-cli/src/main/kotlin/org/factcast/schema/registry/cli/project/impl/ProjectServiceImpl.kt
- factcast-schema-registry-cli/src/main/kotlin/org/factcast/schema/registry/cli/project/structure/EventFolder.kt
- factcast-schema-registry-cli/src/main/kotlin/org/factcast/schema/registry/cli/project/structure/EventVersionFolder.kt
- factcast-schema-registry-cli/src/main/kotlin/org/factcast/schema/registry/cli/project/structure/Folder.kt
- factcast-schema-registry-cli/src/main/kotlin/org/factcast/schema/registry/cli/project/structure/NamespaceFolder.kt
- factcast-schema-registry-cli/src/main/kotlin/org/factcast/schema/registry/cli/project/structure/ProjectFolder.kt
- factcast-schema-registry-cli/src/main/kotlin/org/factcast/schema/registry/cli/project/structure/TransformationFolder.kt
- factcast-schema-registry-cli/src/main/kotlin/org/factcast/schema/registry/cli/whitelistfilter/WhiteList.kt
- factcast-schema-registry-cli/src/main/kotlin/org/factcast/schema/registry/cli/whitelistfilter/WhiteListFilterServiceImpl.kt
- factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/whitelistfilter/WhiteListTest.kt
improved whitelist filtering which moves the question "Am I a valid path?" to the folder itself.
> Issue1092 whitelist improvement

- factcast-client-grpc-cli/src/main/java/org/factcast/client/grpc/cli/conv/Converters.java
- factcast-core/src/main/java/org/factcast/core/subscription/ReconnectingFactSubscriptionWrapper.java
- factcast-examples/factcast-example-server-basicauth/pom.xml
- factcast-examples/factcast-example-server/pom.xml
- factcast-examples/factcast-example-tls-server/pom.xml
- factcast-factus/src/main/java/org/factcast/factus/FactusImpl.java
- factcast-factus/src/main/java/org/factcast/factus/lock/Locked.java
- factcast-factus/src/main/java/org/factcast/factus/projection/LocalWriteToken.java
- factcast-factus/src/main/java/org/factcast/factus/projector/DefaultProjector.java
- factcast-factus/src/main/java/org/factcast/factus/snapshot/AbstractSnapshotRepository.java
- factcast-factus/src/test/java/org/factcast/factus/snapshot/AggregateSnapshotRepositoryImplTest.java
- factcast-grpc-api/src/main/java/org/factcast/grpc/api/Capabilities.java
- factcast-itests/factcast-itests-factus/pom.xml
- factcast-itests/factcast-itests-novalidation/pom.xml
- factcast-itests/factcast-itests-tls/pom.xml
- factcast-itests/factcast-itests-transformation/pom.xml
- factcast-server-grpc/src/main/java/org/factcast/server/grpc/FactcastRemoteException.java
- factcast-site/documentation/content/changelog1.md
- factcast-snapshotcache-redisson/pom.xml
- factcast-store-pgsql/pom.xml
- factcast-test/pom.xml
- factcast-test/src/main/java/org/factcast/test/FactCastExtension.java
- factcast-test/src/main/java/org/factcast/test/RedisExtension.java
- pom.xml
> fix npe on class name usage

- factcast-server-grpc/src/main/java/org/factcast/server/grpc/BlockingStreamObserver.java
> #1233: improved logging and readability (hopefully)

- factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/registry/validation/schema/store/PgSchemaStoreImpl.java
- factcast-store-pgsql/src/test/java/org/factcast/store/pgsql/registry/validation/schema/store/PgSchemaStoreImplTest.java
> 1252: nearcache in schemastore

- factcast-snapshotcache-redisson/src/main/java/org/factcast/core/snap/redisson/RedissonSnapshotCache.java
- factcast-snapshotcache-redisson/src/test/java/org/factcast/core/snap/redisson/RedissonSnapshotCacheTest.java
> Issue1342: Use redis native TTL in RedisSnapshotCache

- factcast-factus/src/main/java/org/factcast/factus/metrics/TagKeys.java
- factcast-site/documentation/content/factus/metrics.md
- factcast-site/documentation/content/setup/server/metrics.md
adds documentation about the metrics currently exposed by Factus
> Issue1347 missing factus metric docs

- factcast-examples/factcast-example-server/src/main/resources/application.properties
- factcast-store-pgsql/src/main/resources/db/changelog/db.changelog-master.yaml
> #1386: fixed liquibase change definition

- factcast-factus-redis/src/main/java/org/factcast/factus/redis/batch/RedissonBatchManager.java
- factcast-factus-redis/src/main/java/org/factcast/factus/redis/tx/RedissonTxManager.java
- factcast-factus-redis/src/test/java/org/factcast/factus/redis/batch/RedissonBatchManagerTest.java
- factcast-factus-redis/src/test/java/org/factcast/factus/redis/tx/RedissonTxManagerTest.java
- factcast-factus-spring-tx/src/main/java/org/factcast/factus/spring/tx/SpringTxManager.java
- factcast-factus-spring-tx/src/test/java/org/factcast/factus/spring/tx/SpringTxManagerTest.java
> Reset tx/batch to null in order to allow client to retry

- factcast-client-grpc/src/main/java/org/factcast/client/grpc/FactCastGrpcClientProperties.java
- factcast-client-grpc/src/main/java/org/factcast/client/grpc/GrpcFactStore.java
- factcast-client-grpc/src/test/java/org/factcast/client/grpc/GrpcFactStoreTest.java
- factcast-examples/factcast-example-client-spring-boot2/src/main/java/org/factcast/example/client/spring/boot2/hello/HelloWorldRunner.java
- factcast-examples/factcast-example-client-spring-boot2/src/main/resources/application.properties
- factcast-grpc-api/src/main/java/org/factcast/grpc/api/Headers.java
- factcast-server-grpc/src/main/java/org/factcast/server/grpc/FactStoreGrpcService.java
- factcast-server-grpc/src/main/java/org/factcast/server/grpc/GrpcObserverAdapter.java
- factcast-server-grpc/src/main/java/org/factcast/server/grpc/GrpcRequestMetadata.java
- factcast-server-grpc/src/main/java/org/factcast/server/grpc/GrpcServerExceptionInterceptor.java
- factcast-server-grpc/src/main/java/org/factcast/server/grpc/ServerExceptionHelper.java
- factcast-server-grpc/src/test/java/org/factcast/server/grpc/FactStoreGrpcServiceTest.java
- factcast-server-grpc/src/test/java/org/factcast/server/grpc/GrpcObserverAdapterTest.java
- factcast-server-grpc/src/test/java/org/factcast/server/grpc/GrpcRequestMetadataTest.java
- factcast-site/documentation/content/setup/properties.md
- factcast-spring-boot-autoconfigure/src/main/java/org/factcast/spring/boot/autoconfigure/client/grpc/GrpcFactStoreAutoConfiguration.java
- factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/PgFactStream.java
- factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/catchup/PgCatchUpPrepare.java
- factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/catchup/tmppaged/PgTmpPagedCatchup.java
- factcast-store-pgsql/src/test/java/org/factcast/store/pgsql/internal/PgFactStreamTest.java
> issue1388: added client.id to grpc metadata & added in loglines

- factcast-core/src/main/java/org/factcast/core/subscription/SubscriptionImpl.java
- factcast-core/src/test/java/org/factcast/core/subscription/SubscriptionImplTest.java
- factcast-examples/factcast-example-client-spring-boot2/src/main/java/org/factcast/example/client/spring/boot2/hello/HelloWorldRunner.java
- factcast-examples/factcast-example-server/src/main/resources/application.properties
- factcast-itests/factcast-itests-exception-handling/src/test/java/org/factcast/itests/exception/handling/ExceptionHandlingV4.java
- factcast-store-pgsql/pom.xml
- factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/PgFactStoreInternalConfiguration.java
- factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/PgFactStream.java
- factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/PgMetrics.java
- factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/PgSubscriptionFactory.java
- factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/StoreMetrics.java
- factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/catchup/PgCatchupFactory.java
- factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/catchup/fetching/PgFetchingCatchUpFactory.java
- factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/catchup/fetching/PgFetchingCatchup.java
- factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/catchup/tmppaged/PgTmpPagedCatchUpFactory.java
- factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/catchup/tmppaged/PgTmpPagedCatchup.java
- factcast-store-pgsql/src/main/resources/db/changelog/db.changelog-master.yaml
- factcast-store-pgsql/src/main/resources/db/changelog/factcast/issue1354/snapshotcache_last_access_index.sql
- factcast-store-pgsql/src/main/resources/db/changelog/factcast/issue1354/transformationcache_last_access_index.sql
- factcast-store-pgsql/src/test/java/org/factcast/store/pgsql/internal/PgFactStreamTest.java
- factcast-store-pgsql/src/test/java/org/factcast/store/pgsql/internal/catchup/fetching/PgFetchingCatchupTest.java
- factcast-store-pgsql/src/test/resources/test_schema.sql
- factcast-test/pom.xml
- factcast-test/src/main/java/org/factcast/test/BaseIntegrationTestExtension.java
- factcast-test/src/main/java/org/factcast/test/FactcastTestConfig.java
- factcast-test/src/main/java/org/factcast/test/Slf4jHelper.java
> issue1354: metrics & logging (also some index cleanup)

- factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/StoreMetrics.java
- factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/snapcache/PgSnapshotCache.java
- factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/snapcache/PgSnapshotCacheConfiguration.java
> issue1281: compaction metrics

- factcast-site/documentation/content/factus/projections.md
The projection.png is missing, could not find a better one / or the sources for the image, replaced it with the ph_p.png .
> Update image link in projections.md

- .github/workflows/format.yml
> Issue1546 commit reformat

- factcast-store/src/main/java/org/factcast/store/internal/catchup/fetching/PgFetchingCatchup.java
- factcast-store/src/main/java/org/factcast/store/internal/catchup/tmppaged/PgTmpPagedCatchup.java
- factcast-store/src/test/java/org/factcast/store/internal/catchup/fetching/PgFetchingCatchupTest.java
- factcast-store/src/test/java/org/factcast/store/internal/catchup/tmppaged/PgTmpPagedCatchupTest.java
> WIP: Fix catchupFact metric calculation

- factcast-server-grpc/src/main/java/org/factcast/server/grpc/FactStoreGrpcService.java
> #1726: lower log level for client side permissions issues

- factcast-site/documentation-docsy/content/en/Usage/factus/setup.md
For merging from main to master
> issue1632 document-binary-serializer-configuration

- factcast-docker/pom.xml
- factcast-docker/release.sh
- factcast-grpc-api/pom.xml
- factcast-hugo/pom.xml
- pom.xml
updated protoc&grpc libs
switched to fabric8.io maven docker plugin
> WIP #1716: M1 Compat

- pom.xml
We will upgrade GRPC for the 0.5 release.
> rollback grpc versions

- factcast-schema-registry-cli/__snapshot__/filter-complex.snap
- factcast-schema-registry-cli/__snapshot__/filter-oneof.snap
- factcast-schema-registry-cli/__snapshot__/filter-should-not-filter-title-property.snap
- factcast-schema-registry-cli/src/main/kotlin/org/factcast/schema/registry/cli/utils/filterJson.kt
- factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/registry/impl/IndexFileCalculatorImplTest.kt
- factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/utils/FilterJsonTest.kt
> #1785: Fix removing of properties with proper schema on the list

- factcast-server-grpc/pom.xml
- factcast-server-grpc/src/main/java/org/factcast/server/grpc/FactStoreGrpcService.java
- factcast-server-grpc/src/test/java/org/factcast/server/grpc/FactStoreGrpcServiceTest.java
cherry-picked https://github.com/factcast/factcast/pull/1663/commits/75c1e34e5cf20e72cd776a37119428da59be0e29 and added tests
> #1162 Harden Grpc layer

- factcast-schema-registry-cli/src/main/kotlin/org/factcast/schema/registry/cli/validation/TransformationEvaluator.kt
- factcast-schema-registry-cli/src/main/kotlin/org/factcast/schema/registry/cli/validation/validators/impl/TransformationValidationServiceImpl.kt
- factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/validation/TransformationEvaluatorIntTest.kt
- factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/validation/TransformationEvaluatorTest.kt
- factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/validation/validators/impl/TransformationValidationServiceImplTest.kt
- factcast-schema-registry-cli/src/test/resources/fixtures/transformation/skipped.js
> Add possibility for skipping transformations check during schema-reg cli validation

- factcast-store/src/main/java/org/factcast/store/internal/PgFactStream.java
- factcast-store/src/test/java/org/factcast/store/internal/PgFactStreamTest.java
when notifyElement throws an exception
> #1851: do not get from closed rs to set serial

- factcast-store/src/main/java/org/factcast/store/registry/transformation/chains/GraalJsTransformer.java
- factcast-store/src/main/java/org/factcast/store/registry/transformation/chains/NashornCompatContextBuilder.java
- factcast-store/src/test/java/org/factcast/store/registry/transformation/chains/GraalJsTransformerTest.java
> WIP #1905: Nested arrays in newly created objects dont get transformed properly 

- factcast-client-grpc-cli/pom.xml
- factcast-client-grpc/pom.xml
- factcast-client-grpc/src/main/java/org/factcast/client/grpc/ResilientGrpcSubscription.java
- factcast-client-grpc/src/test/java/org/factcast/client/grpc/GrpcFactStoreTest.java
- factcast-client-grpc/src/test/java/org/factcast/client/grpc/ResilienceTest.java
- factcast-core/pom.xml
- factcast-core/src/main/java/org/factcast/core/FactCast.java
- factcast-core/src/main/java/org/factcast/core/ReadFactCast.java
- factcast-core/src/test/java/org/factcast/core/spec/FactSpecTest.java
- factcast-core/src/test/java/org/factcast/core/subscription/SubscriptionClosedExceptionTest.java
- factcast-factus-bin-snapser/pom.xml
- factcast-factus-event/pom.xml
- factcast-factus-redis/pom.xml
- factcast-factus-spring-tx/pom.xml
- factcast-factus/pom.xml
- factcast-grpc-api/pom.xml
- factcast-schema-registry-maven-plugin/pom.xml
- factcast-snapshotcache-redisson/pom.xml
- factcast-spring-boot-autoconfigure/pom.xml
- factcast-test-redis/pom.xml
- factcast-test-redis/src/main/java/org/factcast/test/redis/RedisIntegrationTestExtension.java
- factcast-test/pom.xml
- factcast-test/src/main/java/org/factcast/test/BaseIntegrationTestExtension.java
- factcast-test/src/main/java/org/factcast/test/FactCastExtension.java
- factcast-test/src/main/java/org/factcast/test/FactCastIntegrationTestExtension.java
- pom.xml
in order to not (yet) force people onto 11 or later.
> Issue2014 make client relevant modules work with Java8

- factcast-store/src/main/java/org/factcast/store/registry/AbstractSchemaRegistry.java
- factcast-store/src/main/java/org/factcast/store/registry/validation/FactValidationAspect.java
- factcast-store/src/test/java/org/factcast/store/registry/validation/FactValidationAspectTest.java
> 2098 schema caching fix

- factcast-store/src/main/java/org/factcast/store/registry/transformation/cache/PgTransformationCache.java
- factcast-store/src/test/java/org/factcast/store/registry/transformation/cache/PgTransformationCacheTest.java
> #2158: flush buffer if necessary also for findAll

- factcast-server-grpc/src/main/java/org/factcast/server/grpc/FactCastSecurityConfiguration.java
- factcast-site/documentation-docsy/content/en/Setup/docker.md
> #1791: update docker docs & fix broken doc link

- factcast-store/src/main/java/org/factcast/store/registry/transformation/cache/PgTransformationCache.java
> #2338: Avoid OOM/overflow

- renovate.json
> #2344: add 0.7-sink as renovate target

- factcast-store/src/main/java/org/factcast/store/internal/tail/PGTailIndexManagerImpl.java
- factcast-store/src/test/java/org/factcast/store/internal/tail/PGTailIndexManagerImplTest.java
So far just the unit test was fixed to verify the bug. I'll implement a solution tomorrow
> 2571: fix creation of tail indexes based on oldest index

- factcast-docker/pom.xml
- factcast-docker/release.sh
> 2579: remove docker release script and reenable docker pushing

- factcast-server-ui/README.md
- factcast-server-ui/pom.xml
- factcast-server-ui/src/main/java/org/factcast/server/ui/full/FullQueryPage.java
- factcast-server-ui/src/test/java/org/factcast/server/ui/AbstractBrowserTest.java
- factcast-server-ui/src/test/java/org/factcast/server/ui/full/FullQueryPageIntTest.java
Adds a button for downloading the query result as json.
The button is inactive until a query is executed.
> UI playground filedownload

- factcast-store/src/main/java/org/factcast/store/internal/PgFactStore.java
- factcast-store/src/main/java/org/factcast/store/internal/PgFactStoreInternalConfiguration.java
- factcast-store/src/test/java/org/factcast/store/internal/PgFactStoreTest.java
…work properlyto make SET LOCAL properly
> #2757-tx-fix: wrap enumerateNamespacesFromPg in TX 

- factcast-itests/factcast-itests-exception-handling/src/test/java/org/factcast/itests/exception/handling/ExceptionHandlingV4.java
Relax timeout value ~and checking behavior~ after noticing it was too strict for some machines (mine), see https://github.com/factcast/factcast/issues/2832
> #2832: relax errorLatch assertion timeout

- factcast-factus/src/main/java/org/factcast/factus/FactusImpl.java
- factcast-factus/src/test/java/org/factcast/factus/FactusImplTest.java
> #2874: only persists ffwd if there was ever a state or facts applied

- factcast-factus/src/main/java/org/factcast/factus/serializer/JacksonSnapshotSerializer.java
- factcast-factus/src/main/java/org/factcast/factus/snapshot/AggregateSnapshotRepositoryImpl.java
- factcast-factus/src/main/java/org/factcast/factus/snapshot/ProjectionSnapshotRepositoryImpl.java
> 2612: onBeforeSnapshot duplication removed

- factcast-store/src/test/java/org/factcast/store/internal/PgFactStoreIntegrationTest.java
Trying to take a potential time drift into account
> #2944: respect os-db time drift

- factcast-spring-boot-autoconfigure/src/main/java/org/factcast/spring/boot/autoconfigure/client/grpc/LZ4cClientAutoConfiguration.java
- factcast-spring-boot-autoconfigure/src/main/java/org/factcast/spring/boot/autoconfigure/client/grpc/SnappycClientAutoConfiguration.java
- factcast-spring-boot-autoconfigure/src/main/java/org/factcast/spring/boot/autoconfigure/server/grpc/LZ4cServerAutoConfiguration.java
- factcast-spring-boot-autoconfigure/src/main/java/org/factcast/spring/boot/autoconfigure/server/grpc/SnappycServerAutoConfiguration.java
- factcast-spring-boot-autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
> #2974: [Compression] Register auto configurations and make them work

- factcast-store/src/main/java/org/factcast/store/internal/telemetry/PgStoreTelemetry.java
> #3024: replace singleThreadExec by fixedTP(1)

- factcast-core/src/main/java/org/factcast/core/snap/Snapshot.java
- factcast-core/src/main/java/org/factcast/core/snap/SnapshotId.java
> #3037: add Snapshot/Id classes again

- factcast-bom/pom.xml
- factcast-client-grpc/pom.xml
- factcast-factus-bin-snapser/pom.xml
- factcast-grpc-api/pom.xml
- factcast-server-grpc/pom.xml
- factcast-snapshotcache-redisson/pom.xml
- factcast-spring-boot-autoconfigure/pom.xml
> #3038: remove net.jpountz l4 dep in favour of java-lz4

- factcast-core/src/main/java/org/factcast/core/subscription/TransformationException.java
- factcast-store/src/main/java/org/factcast/store/registry/transformation/FactTransformerServiceImpl.java
- factcast-store/src/main/java/org/factcast/store/registry/transformation/chains/TransformationChain.java
- factcast-store/src/test/java/org/factcast/store/registry/transformation/FactTransformerServiceImplTest.java
> #3071: add context to TransformationException

- factcast-core/src/main/java/org/factcast/core/spec/FactSpec.java
- factcast-core/src/main/java/org/factcast/core/subscription/SubscriptionRequestTO.java
- factcast-core/src/test/java/org/factcast/core/spec/FactSpecTest.java
- factcast-core/src/test/java/org/factcast/core/subscription/SubscriptionRequestTOTest.java
- factcast-store-test/src/main/java/org/factcast/store/test/AbstractFactStoreTest.java
- factcast-store/src/main/java/org/factcast/store/internal/PostQueryMatcher.java
- factcast-store/src/test/java/org/factcast/store/internal/PgTokenStoreTest.java
- factcast-store/src/test/java/org/factcast/store/internal/filter/FactSpecMatcherTest.java
> Issue3069 remove js filter script

- factcast-store/src/main/java/org/factcast/store/internal/filter/blacklist/Blacklist.java
Before:
100K entries take 9s on my machine
200k ~40s 
After:
200k instant
20mio ~500ms
closes #3138
> #3138: switch to hashset instead of CopyOnWriteArraySet

- factcast-site/documentation-docsy/content/en/Setup/Migration Guides/0.8.0.md
> #3174: fix broken link

- factcast-site/documentation-docsy/content/en/Setup/Migration Guides/0.8.0.md
> #3180: add pg version note to migration guide

- factcast-site/documentation-docsy/content/en/Setup/Migration Guides/0.8.0.md
- factcast-site/documentation-docsy/content/en/Usage/HitchhikersGuide/extend-projection-db-support.md
> #3182: add removal of compression deps to migration guide

- factcast-site/documentation-docsy/content/en/Usage/factus/projections/snapshots/_index.md
> docs for spring based snapshot serializer

- factcast-site/documentation-docsy/content/en/About/migration.md
Adding section about changes in snapshot serialization to migration guide.
> #3196: issue3196 snapshot serialization in migration guide

- factcast-snapshotcache-redisson/src/main/java/org/factcast/core/snap/redisson/RedissonSnapshotProperties.java
> #3260: remove deprecated annotation

- factcast-bom/pom.xml
- factcast-client-grpc/src/main/java/org/factcast/client/grpc/GrpcFactStore.java
- factcast-core/src/main/java/org/factcast/core/spec/FactSpec.java
- factcast-core/src/test/java/org/factcast/core/spec/FactSpecTest.java
- factcast-examples/factcast-example-client-spring-boot2/src/main/java/org/factcast/example/client/spring/boot2/hello/HelloWorldRunner.java
- factcast-factus/src/main/java/org/factcast/factus/projector/ProjectorImpl.java
- factcast-factus/src/test/java/org/factcast/factus/projector/ProjectorImplTest.java
- factcast-grpc-api/src/main/proto/FactStore.proto
- factcast-itests/factcast-itests-factus/src/test/java/org/factcast/itests/factus/event/UserFired.java
- factcast-itests/factcast-itests-factus/src/test/java/org/factcast/itests/factus/filtering/FilteringTest.java
- factcast-itests/factcast-itests-factus/src/test/java/org/factcast/itests/factus/proj/LocalUserNamesFilterByMultipleAggregateIds.java
- factcast-server-grpc/src/main/java/org/factcast/server/grpc/FactStoreGrpcService.java
- factcast-store-test/src/main/java/org/factcast/store/test/AbstractFactStoreTest.java
- factcast-store/src/main/java/org/factcast/store/internal/filter/FactSpecMatcher.java
- factcast-store/src/main/java/org/factcast/store/internal/query/PgQueryBuilder.java
- factcast-store/src/test/java/org/factcast/store/internal/PgTokenStoreTest.java
- factcast-store/src/test/java/org/factcast/store/internal/filter/FactSpecMatcherTest.java
- factcast-store/src/test/java/org/factcast/store/internal/query/PgQueryBuilderTest.java
> Add support for multiple aggIds in FactSpecs

- factcast-bom/pom.xml
- factcast-test-dynamo/pom.xml
- factcast-test-redis/pom.xml
> test scope fixed in bom

- factcast-factus/src/main/java/org/factcast/factus/FactusImpl.java
> #3312: remove duplicated timer

- factcast-core/src/main/java/org/factcast/core/spec/FactSpec.java
> issue3327 readd missing signature aggId(UUID)

- factcast-snapshotcache-jdbc/src/main/java/org/factcast/core/snap/jdbc/JdbcSnapshotCache.java
- factcast-snapshotcache-jdbc/src/test/java/org/factcast/core/snap/jdbc/JdbcSnapshotCacheTest.java
- factcast-snapshotcache-local-disk/src/main/java/org/factcast/core/snap/local/InMemoryAndDiskSnapshotCache.java
- factcast-snapshotcache-local-disk/src/main/java/org/factcast/core/snap/local/SnapshotFileHelper.java
- factcast-snapshotcache-local-disk/src/test/java/org/factcast/core/snap/local/InMemoryAndDiskSnapshotCacheTest.java
- factcast-snapshotcache-local-disk/src/test/java/org/factcast/core/snap/local/SnapshotDiskRepositoryImplTest.java
- factcast-snapshotcache-local-disk/src/test/java/org/factcast/core/snap/local/SnapshotFileHelperTest.java
- factcast-snapshotcache-redisson/src/main/java/org/factcast/core/snap/redisson/RedissonSnapshotCache.java
- factcast-snapshotcache-redisson/src/test/java/org/factcast/core/snap/redisson/RedissonSnapshotCacheTest.java
> #3335: consider ProjectionMetaData in snapshot cache key creation

- factcast-store/src/main/java/org/factcast/store/internal/StoreMetrics.java
- factcast-store/src/main/resources/db/changelog/db.changelog-master.yaml
- factcast-store/src/main/resources/db/changelog/factcast/issue3033/drop_snapshot_cache.sql
- factcast-store/src/test/resources/wipe.sql
> #3033: cleanup snapshot cache

- factcast-store/src/main/java/org/factcast/store/registry/transformation/TransformationConfiguration.java
- factcast-store/src/main/java/org/factcast/store/registry/transformation/cache/InMemTransformationCache.java
- factcast-store/src/main/java/org/factcast/store/registry/transformation/cache/PgTransformationCache.java
- factcast-store/src/test/java/org/factcast/store/registry/transformation/cache/PgTransformationCacheITest.java
- factcast-store/src/test/java/org/factcast/store/registry/transformation/cache/PgTransformationCacheTest.java
> #3279: lock table when flushing

- .github/kts/maven.main.kts
- .github/workflows/maven.yaml
> Include pg16 in test matrix

- .github/kts/maven.main.kts
- .github/workflows/maven.yaml
> #3398: pg16->17

- factcast-factus/src/main/java/org/factcast/factus/lock/Locked.java
- factcast-factus/src/main/java/org/factcast/factus/lock/RetryableTransaction.java
- factcast-factus/src/main/java/org/factcast/factus/lock/RetryableTransactionImpl.java
- factcast-factus/src/test/java/org/factcast/factus/lock/RetryableTransactionImplTest.java
- factcast-itests/factcast-itests-factus/src/test/java/org/factcast/itests/factus/client/FactusClientTest.java
> Issue3485 add onSuccess callback to transaction

- factcast-core/src/main/java/org/factcast/core/subscription/observer/FastForwardTarget.java
- factcast-core/src/main/java/org/factcast/core/subscription/observer/HighWaterMark.java
- factcast-core/src/test/java/org/factcast/core/subscription/observer/FastForwardTargetTest.java
- factcast-store/src/main/java/org/factcast/store/internal/PgFactStream.java
- factcast-store/src/main/java/org/factcast/store/internal/tail/FastForwardTargetRefresher.java
- factcast-store/src/test/java/org/factcast/store/internal/PgFactStreamTelemetryTest.java
- factcast-store/src/test/java/org/factcast/store/internal/PgFactStreamTest.java
- factcast-store/src/test/java/org/factcast/store/internal/tail/FastForwardTargetRefresherTest.java
> #3722: fix ffwd glitch

- factcast-client-grpc/src/main/java/org/factcast/client/grpc/ResilientGrpcSubscription.java
- factcast-itests/factcast-itests-factus/src/test/java/org/factcast/itests/factus/client/ExceptionOnHandshakeTest.java
> #3800: fail properly on handshake error

- factcast-store/src/main/java/org/factcast/store/internal/PgConstants.java
**Backport:** https://github.com/factcast/factcast/pull/3783
> [0.9.9-release] #3782: add fastUpdate=false if disabled

- factcast-factus/src/main/java/org/factcast/factus/FactusImpl.java
- factcast-factus/src/test/java/org/factcast/factus/FactusImplTest.java
> explicit exception when locking non-existing aggregate

- factcast-store/src/main/java/org/factcast/store/registry/metrics/RegistryMetrics.java
- factcast-store/src/main/java/org/factcast/store/registry/metrics/RegistryMetricsImpl.java
- factcast-store/src/main/java/org/factcast/store/registry/transformation/cache/CacheBuffer.java
- factcast-store/src/main/java/org/factcast/store/registry/transformation/cache/PgTransformationCache.java
- factcast-store/src/test/java/org/factcast/store/registry/NOPRegistryMetrics.java
- factcast-store/src/test/java/org/factcast/store/registry/metrics/RegistryMetricsImplTest.java
- factcast-store/src/test/java/org/factcast/store/registry/transformation/cache/CacheBufferTest.java
- factcast-store/src/test/java/org/factcast/store/registry/transformation/cache/PgTransformationCacheITest.java
- factcast-store/src/test/java/org/factcast/store/registry/transformation/chains/NOPRegistryMetrics.java
> #3885: fix inconsistency window for TransformationCache

- factcast-server-ui/package.json
- factcast-store/src/main/java/org/factcast/store/internal/PgFactStream.java
- factcast-store/src/main/java/org/factcast/store/internal/PgSubscriptionFactory.java
- factcast-store/src/test/java/org/factcast/store/internal/PgFactStreamTelemetryTest.java
- factcast-store/src/test/java/org/factcast/store/internal/PgFactStreamTest.java
- factcast-store/src/test/java/org/factcast/store/internal/PgSubscriptionFactoryTest.java
> #3935: fix NPE

- factcast-itests/factcast-itests-factus/src/test/java/org/factcast/itests/factus/client/FactusClientTest.java
- factcast-itests/factcast-itests-factus/src/test/java/org/factcast/itests/factus/event/film/SubscribedLucasNames.java
- factcast-store/src/main/java/org/factcast/store/internal/CondensedQueryExecutor.java
- factcast-store/src/test/java/org/factcast/store/internal/CondensedQueryExecutorTest.java
> #3952 Allow wildcards when subscribing in ns and/or type
