factcast/factcast

- factcast-site/documentation/serve.sh
The "resources" folder is created for "root" group otherwise.
> Let the hugo container create and serve files with host users groupid

- factcast-site/documentation/content/concept/fact.md
- factcast-site/documentation/content/migration/_index.md
> #788: documentation clarification

- factcast-docker/pom.xml
To make this work you have to add an additonal server to the mvn settings of the release machine.  
Something like
```
<server>
<id>docker-hub</id>
<username>foo</username>
<password>secret-password</password>
<configuration>
<email>foo@foo.bar</email>
</configuration>
</server>
```
Closes #884
> #884: Publish docker image during release

- factcast-site/documentation/content/setup/properties.md
- factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/PgConfigurationProperties.java
- factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/CondensedQueryExecutor.java
- factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/PgConstants.java
- factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/PgFactStoreInternalConfiguration.java
- factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/listen/PgListener.java
- factcast-store-pgsql/src/test/java/org/factcast/store/pgsql/internal/listen/PgListenerTest.java
With FC, we should have a test roundtrip that makes sure that postgres listeners are not stale or must be reconnected. This will be done to make sure the database is not the reason for stale/slow consumers. 
AC: FactCast tests his database listeners continously an detects possible stale connections
AC: Detected staleness is mitigated immediately
AC: All active consumers are triggered for a re-query if stale listeners were detected
> Issue941 - Implement Keepalive roundtrip to detect stale postgres listeners

- factcast-client-grpc/src/main/java/org/factcast/client/grpc/GrpcFactStore.java
- factcast-client-grpc/src/main/java/org/factcast/client/grpc/codec/Lz4GrpcClientCodec.java
- factcast-client-grpc/src/test/java/org/factcast/client/grpc/GrpcFactStoreTest.java
- factcast-grpc-api/src/main/java/org/factcast/grpc/api/Headers.java
- factcast-server-grpc/src/main/java/org/factcast/server/grpc/BlockingStreamObserver.java
- factcast-server-grpc/src/main/java/org/factcast/server/grpc/FactStoreGrpcService.java
- factcast-server-grpc/src/main/java/org/factcast/server/grpc/GrpcCompressionInterceptor.java
- factcast-server-grpc/src/main/java/org/factcast/server/grpc/codec/Lz4GrpcServerCodec.java
- factcast-server-grpc/src/test/java/org/factcast/server/grpc/GrpcCompressionInterceptorTest.java
call compression was working on request, but not response due to missing call headers.
> #959: fix response compression, add some tracing

- factcast-bom/pom.xml
- factcast-core/pom.xml
- factcast-internal-dep/pom.xml
- factcast-itests/factcast-itests-factus/pom.xml
- factcast-schema-registry-cli/pom.xml
- factcast-schema-registry-maven-plugin/pom.xml
- pom.xml
Some POM cleanups regarding jackson which hopefully reduce the amount of PRs and other integration runs on the next version bump if I didn't miss a spot.
Another build warning fix for testcontainers and moved slf4j dependency around also reducing the amount of touched files on version bump.
Let me know if you want these separate from each other.
> Pom cleanups

- factcast-schema-registry-cli/src/main/kotlin/org/factcast/schema/registry/cli/validation/TransformationEvaluator.kt
- factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/validation/TransformationEvaluatorTest.kt
- factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/registry/transformation/chains/NashornTransformer.java
- factcast-store-pgsql/src/test/java/org/factcast/store/pgsql/registry/transformation/chains/NashornTransformerTest.java
- factcast-store-pgsql/src/test/java/org/factcast/store/pgsql/registry/transformation/chains/TransformationChainsTest.java
Currently Factcast includes a bug, where event transformations that add a new array are handled incorrectly.
When using a transformation function like this:
```js
function transform(event) {
event.newField = [1 ,2 ,3];
}
```
the new field would be transformed to
```json
{
"newField" : {
"0": 1,
"1": 2,
"2": 3
}
}
```
This happens as Jackson mishandles the Nashorn internal `ScriptObjectMirror`, which is an array if `ScriptObjectMirror#isArray == true` and an object otherwise. As it however implements `Map` internally, Jackson treats it as a Map.
---
Implementation note: I decided against telling Jackson how to treat this `ScriptObjectMirror` as I for one did not want to touch the `FactCastJson` class due to the "do not change mapper" comment and it kind of felt wrong to configure Jackson …
> Fix transform handling when adding a new array

- factcast-schema-registry-cli/src/main/kotlin/org/factcast/schema/registry/cli/validation/TransformationEvaluator.kt
- factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/validation/TransformationEvaluatorTest.kt
- factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/registry/transformation/chains/NashornTransformer.java
- factcast-store-pgsql/src/test/java/org/factcast/store/pgsql/registry/transformation/chains/NashornTransformerTest.java
- factcast-store-pgsql/src/test/java/org/factcast/store/pgsql/registry/transformation/chains/TransformationChainsTest.java
created by olewehrmeyer:
__________
Currently Factcast includes a bug, where event transformations that add a new array are handled incorrectly.
When using a transformation function like this:
```js
function transform(event) {
event.newField = [1 ,2 ,3];
}
```
the new field would be transformed to
```json
{
"newField" : {
"0": 1,
"1": 2,
"2": 3
}
}
```
This happens as Jackson mishandles the Nashorn internal ScriptObjectMirror, which is an array if ScriptObjectMirror#isArray == true and an object otherwise. As it however implements Map internally, Jackson treats it as a Map.
Implementation note: I decided against telling Jackson how to treat this ScriptObjectMirror as I for one did not want to touch the FactCastJson class due to the "do not change mapper" comment and it kind of felt wrong …
> Fix transformation handling when adding a new array

- factcast-store/src/main/java/org/factcast/store/registry/transformation/chains/GraalJsTransformer.java
- factcast-store/src/test/java/org/factcast/store/registry/transformation/chains/GraalJsTransformerTest.java
GraalJS [does not allow concurrent access to engines any more](https://medium.com/graalvm/multi-threaded-java-javascript-language-interoperability-in-graalvm-2f19c1f9c37b).
We will now wait in case two threads share the same engine.
In the rare case n threads try to warm up the engine with the same JS at the same time, they will work with n engines in parallel, but for later we will only keep one of those engines.
> #1506: synchronized access to engines

- factcast-store/src/test/java/org/factcast/store/internal/listen/PgListenerIntegrationTest.java
- factcast-store/src/test/resources/test_schema.sql
This now tests that the tx id is part of the trigger, and is send around in the event on the event bus.
Note: the integration tests in factcast-store do not use the official sql, but a test schema creation file, so changes in the official sql would not turn this test red. My suggestion, however, is to consider fixing this in general, rather than making an exception for this specific test. I'm unaware of the reasons for this separation though.
@uweschaefer any thoughts?
> #1590-integration-test-for-notification-trigger-extension

- factcast-schema-registry-cli/src/main/kotlin/org/factcast/schema/registry/cli/validation/ProjectError.kt
- factcast-schema-registry-cli/src/main/kotlin/org/factcast/schema/registry/cli/validation/formatErrors.kt
- factcast-schema-registry-cli/src/main/kotlin/org/factcast/schema/registry/cli/validation/validators/impl/TransformationValidationServiceImpl.kt
- factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/validation/validators/impl/TransformationValidationServiceImplTest.kt
This MR fixes #1758.
Output will look like this after merge:
```
[INFO] --- factcast-schema-registry-maven-plugin:0.4.3:build (build) @ schema-registry-registry ---
[INFO] Established active environments: [cli]
[INFO] Starting building Factcast Schema Registry
[INFO] Input: src/main/registry
[INFO] 
[ERROR] Exception during transformation of MyEvent from 1 to 2:
javax.script.ScriptException: org.graalvm.polyglot.PolyglotException: TypeError: undefined has no such function "split"
```
> [schema-reg-cli] Catch exceptions during transformation

- factcast-store/src/main/resources/db/changelog/db.changelog-master.yaml
Testing showed that in high load situations, the alter index might not be able to acquire the necessary locks
so that the server startup hangs, or fails.
we'll have to move it to the documentation
> revert gin index optimization

- factcast-itests/factcast-itests-factus/src/test/java/org/factcast/itests/factus/client/DatabaseUnhealthyITest.java
- factcast-server-grpc/src/main/java/org/factcast/server/grpc/GrpcServerExceptionInterceptor.java
- factcast-store/src/main/java/org/factcast/store/internal/PgSubscriptionFactory.java
- factcast-store/src/main/java/org/factcast/store/internal/query/PgLatestSerialFetcher.java
- factcast-store/src/test/java/org/factcast/store/internal/PgLatestSerialFetcherTest.java
- factcast-store/src/test/java/org/factcast/store/internal/query/PgLatestSerialFetcherTest.java
We observed two more occasions of the issue described in #2162.
This time the pattern was easy to identify: it always happened when the postgres (RDS) was not available/caused some kind of `PSQLException` within factcast. In our case this happened due to DB maintenance.
This way I could create a failing test by leveraging our toxiproxy setup. 
We identified two main issues:
- in `PgSubscriptionFactory.java` we catch RuntimeExceptions but the exception from above is none. The client was never notified about an error -> will now be mapped to StatusRuntimeException UNKNOWN
- `PgLatestSerialFetcher.java` swallows just every exception but is used to create the `FactStreamInfo` -> since we use `COALESCE` in our case I think the exception handling is not necessary at this place
Im not quite sure …
> #2162: Mitigate factus.update calls get stuck if server runs into database issues

- factcast-snapshotcache-redisson/pom.xml
- factcast-snapshotcache-redisson/src/main/java/org/factcast/core/snap/redisson/RedissonSnapshotProperties.java
Against expectations java ignores the lazy class loading when using the method reference operator instead of a lambda which is why building fails for clients using the newest version because of missing dependencies. 
This PR reverts that and removes the now not longer required test dependencies.
> 2052: remove unused transitive codec dependencies

- factcast-store/src/main/resources/db/changelog/db.changelog-master.yaml
> #2311: Add valid checksums

- factcast-store/src/main/java/org/factcast/store/internal/listen/PgConnectionSupplier.java
- factcast-store/src/test/java/org/factcast/store/internal/PgTestConfiguration.java
- factcast-store/src/test/java/org/factcast/store/internal/listen/PgConnectionSupplierIntegrationTest.java
- factcast-store/src/test/java/org/factcast/store/internal/listen/PgConnectionSupplierTest.java
> #2336: Make PGConnectionSupplier respect custom connection properties

- factcast-store/src/main/java/org/factcast/store/internal/catchup/BufferingFactInterceptor.java
- factcast-store/src/test/java/org/factcast/store/internal/catchup/BufferingFactInterceptorTest.java
> #2340: Possbile OOM/buffer overflow in BufferingFactInterceptor

- factcast-factus/src/main/java/org/factcast/factus/utils/FactusDependency.java
- factcast-spring-boot-autoconfigure/src/main/java/org/factcast/spring/boot/autoconfigure/core/RedissonAutoConfiguration.java
- factcast-spring-boot-autoconfigure/src/main/java/org/factcast/spring/boot/autoconfigure/factus/FactusAutoConfiguration.java
- factcast-spring-boot-autoconfigure/src/main/java/org/factcast/spring/boot/autoconfigure/redis/RedissonAutoConfiguration.java
- factcast-spring-boot-autoconfigure/src/main/java/org/factcast/spring/boot/autoconfigure/redis/RedissonSnapshotCacheAutoConfiguration.java
- factcast-spring-boot-autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
closes #2381 
superseeds #2383 
This way, people can either implement, or use an indirection (see RedissonAutoConfiguration as an example)  to declare dependencies to Factus the Spring way, without necessarily changing Factcast code.
> Add dependency declaring interface in order to ensure init/destroy order in Spring

- factcast-client-grpc/src/main/java/org/factcast/client/grpc/GrpcFactStore.java
- factcast-client-grpc/src/test/java/org/factcast/client/grpc/GrpcFactStoreTest.java
Missing (and, as discussed with @uweschaefer, also empty) credential parts should cause fast failure on the client side.
> #2931 fail fast on missing credential parts

- factcast-schema-registry-maven-plugin/pom.xml
I removed the second version definition which was overwritten by the first one.
> #2941: remove duplicate version mavenpluginplugin

- factcast-server-ui/src/main/java/org/factcast/server/ui/config/UIConfiguration.java
- factcast-server-ui/src/test/java/org/factcast/server/ui/config/UIConfigurationIntTest.java
See https://github.com/factcast/factcast/issues/3093
Explicitly disable Vaadin React support to reinstate share-able URLs containing filter specifics.
> issue3093 disable React support

- factcast-itests/factcast-itests-factus/src/test/java/org/factcast/itests/factus/client/DynamoITest.java
- factcast-itests/factcast-itests-factus/src/test/java/org/factcast/itests/factus/client/FactusClientTest.java
- factcast-itests/factcast-itests-factus/src/test/java/org/factcast/itests/factus/client/SpringTransactionalITest.java
- factcast-test/src/main/java/org/factcast/test/BaseIntegrationTestExtension.java
Closes #3129 
Fix broken itests after removing serial sequence restart.
> #3129: AbstractFactCastIntegrationTest wipes serial sequence after each test

- pom.xml
Adding Mockito lib as Java agent because starting from Java 21, the [JDK restricts the ability of libraries to attach a Java agent to their own JVM](https://openjdk.org/jeps/451). As a result, the inline-mock-maker might not be able to function without an explicit setup to enable instrumentation, and the JVM will always display a warning.
Note that e.g. [CommandServiceImplTest](https://github.com/factcast/factcast/blob/master/factcast-schema-registry-cli/src/test/kotlin/org/factcast/schema/registry/cli/commands/CommandServiceImplTest.kt) uses MockK which causes the same warning but will not be fixed with the suggested solution.
MockK still has an open issue regarding this, see https://github.com/mockk/mockk/issues/1171
> #3176: add Mockito lib as java agent

- factcast-core/src/main/java/org/factcast/core/FactStreamPosition.java
- factcast-core/src/test/java/org/factcast/core/FactStreamPositionTest.java
- factcast-core/src/test/java/org/factcast/core/TestFact.java
- factcast-factus/src/main/java/org/factcast/factus/FactusImpl.java
- factcast-factus/src/test/java/org/factcast/factus/FactusImplTest.java
- factcast-store/src/main/java/org/factcast/store/internal/PgFactStream.java
- factcast-store/src/test/java/org/factcast/store/internal/PgFactStreamTest.java
- ignore stale ffwd in factus
- only send ffwd if its really a forward
closes #3289
> #3289: FastForward information might be stale but is still applied client-side

- factcast-core/src/main/java/org/factcast/core/FactStreamPosition.java
- factcast-core/src/test/java/org/factcast/core/FactStreamPositionTest.java
- factcast-core/src/test/java/org/factcast/core/TestFact.java
- factcast-factus/src/main/java/org/factcast/factus/FactusImpl.java
- factcast-factus/src/test/java/org/factcast/factus/FactusImplTest.java
- factcast-store/src/main/java/org/factcast/store/internal/PgFactStream.java
- factcast-store/src/test/java/org/factcast/store/internal/PgFactStreamTest.java
**Backport:** https://github.com/factcast/factcast/pull/3291
- ignore stale ffwd in factus
- only send ffwd if its really a forward
closes #3289
> [0.8.3-release] #3289: FastForward information might be stale but is still applied client-side

- factcast-factus-redis/src/main/java/org/factcast/factus/redis/tx/AbstractRedisTxProjection.java
- factcast-itests/factcast-itests-factus/src/test/java/org/factcast/itests/factus/client/FactusClientTest.java
- factcast-itests/factcast-itests-factus/src/test/java/org/factcast/itests/factus/proj/BlockingRedisTxManagedUserNames.java
We already rely on the redis lock to make sure we dont run multiple updates in parallel (across several instances). When we remove the assertion of the running tx the same applies then to multiple update calls for the same jvm/spring context/projection instance.
closes #3361
> #3361: do not throw for parallel update calls of tx redis projections on same instance
